
name: Check for Changes

on:
  schedule:
    - cron: '19 * * * *'
  workflow_dispatch:
  push:
    branches:
    - 'actions-branch'
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: cd cronserver && node checkChanges.js
      env:
        ATLAS_URI: ${{secrets.ATLAS_URI}}
        DB_NAME: ${{secrets.DB_NAME}}
        EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
        EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
        EMAIL_SERVICE: ${{secrets.EMAIL_SERVICE}}

  

